var system = java.lang.System
system.out.println("This is a output generated by the eval rather than InvokeFunction");

function handleIncident(){
  system.out.println("This is the second incidentHandler javascript file output: " + incidentMessage);
}